### ISSUE TITLE
Wrong cursor while dragging horizontally

### ISSUE THREAD

**Issue by jlaurens** [bajaniyarohit/vue-split-panel#1]
The cursor has no chance to ever become a col-resize one.

When you hover a gutter, the cursor appropriately changes to either col-resize of row-resize, according to the css. But as soon as you start dragging, the cursor always switch to row-resize, regardless the direction.

Actually, [line 43 of split.vue](https://github.com/bajaniyarohit/vue-split-panel/blob/4a0dee56d2d202b182b3db870b2433a1aa892141/src/components/split/split.vue#L43) reads

`                cursor: 'row-resize',
`

whereas it should read something like

`                cursor: self.direction === 'horizontal' ? 'col-resize' : 'row-resize',
`

TIA

**Comment by bajaniyarohit** [comment]
Hi @jlaurens 

I have changed on line 43 of split.vue as per your suggested code.
Thanks for your feedback.
